# Generated by Django 5.0 on 2025-10-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0002_observation_created_at_observation_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="source",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("obis", "OBIS"),
                    ("other", "Other External"),
                ],
                default="user",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="validated",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("validated", "Validated"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
