# Generated by Django 5.0 on 2025-10-27 14:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0003_observation_source_observation_validated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observation",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="longitude",
        ),
        migrations.AddField(
            model_name="observation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
