# Generated by Django 5.0 on 2025-10-27 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0004_remove_observation_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional picture of the observed species.",
                null=True,
                upload_to="observation_pics/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
