# Generated by Django 5.0 on 2025-10-27 16:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0005_observation_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default="SRID=4326;POINT (0 0)", geography=True, srid=4326
            ),
            preserve_default=False,
        ),
    ]
