# Generated by Django 5.0 on 2025-10-27 17:00

import django.core.validators
import observations.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0006_alter_observation_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional picture of the observed species (max 2MB, resized to 512x512px).",
                null=True,
                upload_to="observation_pics/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    observations.models.validate_image,
                ],
            ),
        ),
    ]
