# Generated by Django 5.0 on 2025-12-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0007_alter_observation_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observation",
            name="depth",
        ),
        migrations.AddField(
            model_name="observation",
            name="bathymetry",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="common_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="depth_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="depth_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="visibility",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
