# Generated by Django 5.0 on 2025-12-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "observations",
            "0008_remove_observation_depth_observation_bathymetry_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
