# Generated by Django 5.0 on 2025-12-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0009_alter_observation_notes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observation",
            options={"ordering": ["-created_at"]},
        ),
    ]
