# Generated by Django 5.0 on 2025-11-18 16:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CuratedObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("species_name", models.CharField(max_length=255)),
                (
                    "common_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("obis_id", models.CharField(max_length=100, unique=True)),
                ("observation_date", models.DateField(blank=True, null=True)),
                ("observation_datetime", models.DateTimeField(blank=True, null=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "machine_observation",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("validated", models.CharField(blank=True, max_length=128, null=True)),
                ("source", models.CharField(default="OBIS", max_length=50)),
                ("depth", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("visibility", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("image", models.URLField(blank=True, null=True)),
                ("user", models.CharField(blank=True, max_length=255, null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-observation_date"],
                "unique_together": {("obis_id", "source")},
            },
        ),
    ]
