# Generated by Django 5.0 on 2025-11-19 17:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curatedobservation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
