# Generated by Django 5.0 on 2025-11-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0002_alter_curatedobservation_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="curatedobservation",
            old_name="depth",
            new_name="bathymetry",
        ),
        migrations.AddField(
            model_name="curatedobservation",
            name="depth_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="curatedobservation",
            name="depth_min",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
