# Generated by Django 5.0 on 2025-11-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "species",
            "0003_rename_depth_curatedobservation_bathymetry_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="curatedobservation",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=10,
                null=True,
            ),
        ),
    ]
